kind: pipeline
name: build

platform:
  os: linux

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: rkojedzinszky/mac2vendor
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password
    auto_tag: true
